Lambda-School-Labs/foster-together-be

- .gitignore
- env.js
- index.js
- package-lock.json
- package.json
- server/server.js
> Configured index.js to include SSL, included env.js to import .env variables

- env.js
- index.js
> Added check for NODE_ENV in index.js

- index.js
- package.json
> Set up sentry I think.

- package.json
- [] New feature (non-breaking change which adds functionality)
- [] Complete, but not tested (may need new tests)
> Update be dependencies

- index.test.js
- server/server.js
- server/server.test.js
> Database setup

- data/db-config.js
- index.test.js
- package.json
- server/api/neighbors/neighbor-helper.js
- server/api/neighbors/neighbor-helper.test.js
> Neighbor helper

- server/api/admin/admin-helper.js
- server/api/admin/admin-router.js
- server/api/api-router.js
> Admin router

- server/api/admin/admin-helper.js
- server/api/admin/admin-router.js
- [] My code has been reviewed by at least one peer
> added admin helpers

- data/migrations/20200226114958_change-zip-to-string.js
- data/seeds/003_zips.js
- package.json
- server/api/families/family-helper.js
- server/api/families/family-helper.test.js
- server/api/families/family-router.test.js
- server/api/locations/location-helper.js
- server/api/neighbors/neighbor-helper.js
- server/api/neighbors/neighbor-helper.test.js
> Helper functions for cities, states, and zips

- README.md
- env.js
- index.js
- package.json
> Removed https and fs modules, development just running on http now

- server/api/neighbors/neighbor-router.test.js
> Fixed tests for neighbor-router

- middleware/index.js
- middleware/validate-id.js
- middleware/validate-signup.js
- middleware/validate-signup.test.js
- server/api/families/family-router.js
- server/api/neighbors/neighbor-router.js
- server/server.js
Added verification middleware to endpoints, and configured global middleware including custom logger function
- [c] Complete, tested, ready to review and merge
> Verification middleware

- data/knex/knexAWS.js
- data/knex/knextest.js
> small bug fix.

- server/api/auth/login/index.test.js
- server/api/auth/register/index.test.js
> modified test order

- server/api/auth/login/index.test.js
- server/api/auth/register/index.test.js
> trying to get error message again

- server/api/auth/login/index.js
- server/api/auth/login/index.test.js
- server/api/auth/register/index.js
- server/api/auth/register/index.test.js
> send more relevant responses for signin and register routes

- server/api/auth/login/index.js
- server/api/auth/login/middleware.js
- server/api/auth/register/index.js
- server/api/auth/register/index.test.js
- server/api/middleware.js
> Backup auth

- .ebextensions/knex.config
- package.json
Second verse, same as the first.
ebconfig failure.
> added seed and migrate scripts

- .ebextensions/knex.config
Trying the commands with sudo privileges. 
Hopefully the AWS deployment thing.
A prayer and a hope.
> run command as sudo

- .ebextensions/knex.config
> added RDS details

- README.md
AKA: Shamelessly stole B's work on the front end to make this look way better.
Documentation update that provides a better layout and more detailed information about the project. Mostly courtesy of copying and pasting B's excellent work on the front end and minor edits.
> Better Update

- .codeclimate.yml
- middleware/validate-signup.js
A refactor of some middleware and codeclimate settings.
Hopefully improves codeclimate maintainablity score.
> refactored validate-signup, changed code climate settings

- .github/workflows/ci.yml
- middleware/validate-signup.js
- middleware/validate-signup.test.js
- package.json
- server/members/member-router.test.js
Fixed CodeClimate, all checks are working. Code climate working correctly.
> attmept to fix codeclimate again

- package.json
- server/application/email.js
- server/application/index.js
- server/application/index.test.js
- server/application/model.js
- server/application/model.test.js
- server/members/member-router.js
- server/middlewareAndTools.js
Added a route for updating an application status from: Not yet reviewed(1), to: Approved(2), Rejected(3), Not in area(4). 
Fully tested the happy path with tests.  
Also added email integration for status of Approved. Tested by sending emails to labs.fostertogether@gmail.com. HTML and inline styles working correctly. Links to app.fostertogther.co/login correctly. 
Should be storing emails as stringified objects in database and have a route to update them, but future RC I think.
> Can update App Status W/auto approval emails

- server/application/email.js
- server/application/index.test.js
- server/middlewareAndTools.js
>  just adding some error message helpers to see why AWS tests fail

- server/application/index.js
Hoping this gives more descriptive error messages on AWS.
> added validateId middleware to appropriate routes.

- data/migrations/20200410153301_create_users_table.js
Added empty up/down functions to empty migration.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Complete, tested, ready to review and merge
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] There are no merge conflicts
> Training tables
